server/command.go
The auto complete description did not have pop command. 
This PR will add the pop command in autocomplete description.
=> Fix auto complete description

server/command.go
This pull request sets `/todo` to return the list of todos as default, it used to return a help text earlier. 
Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/8
=> command - /todo  returns the list of todos

webapp/src/actions.js
Fix 'When no SiteURL is set in config, the basePath is not properly set'
Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/43
=> [GH43] Fix 'When no SiteURL is set in config, the basePath is not properly set'

webapp/src/components/sidebar_right/todo_issues.jsx
**Summary**
This PR makes sure that, if a word overflows it's container, it will break properly.
- the browser support for `overflow-wrap: break-word` is very good.
**Ticket link**
Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/41
=> [GH-41] Fix text overflow in the side bar

server/command.go
Add missing space to /todo (add|pop) response
- "Added Todo.Todo List:" -> "Added Todo. Todo List:"
- "Removed top Todo.Todo List:" -> "Removed top Todo. Todo List:"
Discovered while working on #4
=> Add missing space to /todo (add|pop) response

server/command.go
Added the following missing commands to the autocomplete suggestion on typing ```/todo```:
1. ```send```
1. ```help```
Before:
After:
Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/64
=> Added missing commands to autocomplete suggestion

webapp/src/index.js
This PR initializes the reducer for the plugin properly to avoid issues with `deep_freeze`.
Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/59
https://mattermost.atlassian.net/browse/MM-24682
=> Move registerReducer call to the top of `initialize`

server/command.go
Allow extra spaces between commands
#83
=> Allow extra spaces between commands

server/command.go
This PR fixes issue 92 posting a response message when there are no Todos to pop instead of unkown error.
closes #92
=> Posting response when there are no Todos to pop instead of unkown error

server/command.go, server/list.go, server/plugin.go
This change adds logic to ensure newly-added todos are in the
returned list. When the Mattermost server running the plugin has
database read replicas configured, it is possible that the plugin
would miss listing the new todo due to replication delay. This
plugin logic attempts to address the issue when it is detected.
I verified this issue and fix by using a dev server with a database
with read replicas configured.
When writing a fix, I went with something that felt like a good
trade-off on code complexity and speed. i.e. I avoided a simple
sleep, but also didn't want to drastically refactor code to fix
the issue in a slightly-better way. All that said, let me know what
you think.
Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/87
=> Handle database replication delay when adding todos

plugin.json
Add ReleaseNotesURL for next Marketplace release. The version number as to be bumped when the next release is cut.
=> Add ReleaseNotesURL

webapp/src/index.js
This pull request will change the channel header button behavior to toggle RHS instead of showing.
https://github.com/mattermost/mattermost-plugin-todo/issues/97
=> Change channel header button to toggle RHS

server/command.go, server/command_test.go
Improve the texts and error messages/behaviours on /todo settings
Current look:
/todo settings
/todo settings summ
/todo settings summary
/todo settings summary on
/todo settings summary off
/todo settings summary foo
/todo settings summary on foo
None
=> Improvement on texts and error behaviours on /todo settings

webapp/src/components/root/root.jsx, webapp/src/components/root/root.scss, webapp/src/components/sidebar_right/sidebar_right.scss
This pull request will adjust the visuals of the plugin, allowing the plugin to adapt to different themes in the application accordingly.  
The style has been adjusted slightly to differentiate the different components in the plugin, and to follow Mattermost's layout more closely.
Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/78
=> Fix plugin visuals to handle different themes

webapp/src/components/channel_header_button/channel_header_button.scss, webapp/src/components/channel_header_button/channel_header_button.tsx
This pull request will fix the channel header icon css when toggled in both scenarios (as an icon, part of drop-down list) by removing the background color for the icon.
Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/104
- As an icon in channel header
- As an item in the drop down list
=> Fix channel header icon highlight

plugin.json, server/manifest.go, webapp/src/manifest.js
Bump version to v0.4.0
Proposal to bump Minor Version to prep for release with the following Release Notes:
* bfa5742 Add telemetry to Todo (#101)
* c865928 Add new plugin setting to toggle button visibility in team sidebar (#114)
* 1905ad5 Change channel header button to toggle RHS (#106)
* bb127b1 GH-88 Add settings command to toggle daily reminders (#90)
* 0e146a1 Mm 91 add active status to header icon (#96)
* b2a69b7 Fix channel header icon highlight (#115)
* 6cce8b3 Fix plugin visuals to handle different themes (#116)
* ccfcd25 Improvement on texts and error behaviours on /todo settings (#110)
* 76cd654 Render correctly linebreaks (#108)
* ba724ab Make internal links to open in the same window, instead of reloading the page (#107)
* ff178b2 Handle database replication delay when …
=> Bump version to 0.4.0

server/command.go
Right now, when a user types a slash command, we store which command the user is typing. To do so, we register the first word after `/zoom`. If a user types wrongly `/zoom Do groceries` instead of `/zoom add Do groceries` we would send to telemetry `Do`.
This ticket fix this.
None
=> Only send commands on command telemetry

server/command.go, server/list.go, server/plugin.go, webapp/src/actions.js, webapp/src/index.js
**Summary**
This PR fixes the issue, where the list of TODO's is not updated in real time on multiple clients. In addition to that, the backend now has full control over refreshing the lists (in, out, my). Therefore it's no longer necessary to do refreshing on the frontend.
**Note:** It would be better, if this PR was merged after [PR-49](https://github.com/mattermost/mattermost-plugin-todo/pull/49), because that one fixes the messages and therefore also the updates.
**Ticket link**
Fixes [#34](https://github.com/mattermost/mattermost-plugin-todo/issues/34)
=> [GH-34] Fix list realtime

plugin.json, server/manifest.go, webapp/src/manifest.js
Version bump to 0.5.0
Features:
d84f619 [GH-82] Add a user preference to disallow incoming Todos (#136)
46c4ee8 [GH-21] Add support markdown preview in add todo modal (#137)
Fixes
23fe723 Improve autocomplete component (#127)
cda3350 [GH-34] Fix list realtime (#50)
f6d9a24 Move the tracking for commands to only send the input command if it is one of the available (#119)
Others
653d9e4 go mod tidy (#141)
1bca666 make apply (#138)
a7665f3 Update plugin.json (#135)
72d5011 Bump ini from 1.3.5 to 1.3.8 in /webapp (#129)
Fix https://github.com/mattermost/mattermost-plugin-todo/issues/128
=> Bump version to 0.5.0

Makefile
There is currently an issue with plugin projects, where CI will timeout during `npm install`. There is an issue with fetching dependencies from GitHub, which is causing this step to take longer than usual. Since CircleCI times out after 10 minutes of no console output, this is causing CI to fail for all webapp plugins.
This PR makes it so use the `--verbose` flag, so the command will have intermediate output, making it so CircleCI does not cancel the build. There is another suggested solution of editing the git config with `git config --global url."ssh://git@".insteadOf git://`, but we have decided to go with the `--verbose` approach instead.
More context here:
https://community-daily.mattermost.com/core/pl/ckmtk65jqjr6p8ahmrk9ggu1gh …
=> `npm install --verbose` to avoid CircleCI timeout

webapp/src/components/buttons/remove.jsx, webapp/src/components/post_type_todo/post_type_todo.jsx, webapp/src/components/sidebar_right/sidebar_right.scss
Updating todo UI fixes
Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/187
Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/186
=> Updating todo UI fixes

webapp/webpack.config.js
For some more context, see [here](https://community.mattermost.com/core/pl/1fkkx7pj1jrwffrc6drh3x71eh). The short version though is that we updated the web app to React 17, and there's a chance that plugins will have some issues with it because they're compiled with the React 16 version of ReactDOM. I'm submitting PRs to the 3 products, the demo plugin, and the plugin template to have them use the web app's version of React DOM to fix any immediate issues, but we'll want to properly migrate them to React 17 going forward.
https://mattermost.atlassian.net/browse/MM-47046
https://github.com/mattermost/mattermost-plugin-playbooks/pull/1489
https://github.com/mattermost/focalboard/pull/3861
https://github.com/mattermost/mattermost-plugin-demo/pull/153 …
=> MM-47046/MM-47052 Use version of React DOM provided by web app

.golangci.yml, go.mod, go.sum, plugin.json, server/manifest.go, webapp/src/manifest.js, webapp/webpack.config.js
https://github.com/mattermost/mattermost-plugin-todo/pull/190
https://github.com/mattermost/mattermost-plugin-todo/issues/192
=> Release 0.6.1

go.mod, go.sum, server/plugin.go, server/serializer.go, webapp/src/actions.js
Added additional checks for POST type APIs in todo plugin.
=> [MM-53425]: Added additional checks for POST type APIs 

server/command.go, server/plugin.go, webapp/src/widget/menu.scss, webapp/src/widget/menu.tsx, webapp/src/widget/menuWrapper.scss, webapp/src/widget/menuWrapper.tsx
Related conversation: https://community.mattermost.com/core/pl/cfk9y3o8jpy9tn4dhz4cd4ioqr
I found that the Todo plugin's css affects the entire `Menu` component.
I applied scope to the `Menu` component.
Fixes https://github.com/mattermost/mattermost/issues/24455
Jira https://mattermost.atlassian.net/browse/MM-54367
=> [MM-54367] Apply scope to the menu class

server/list.go
Change the foreign user id for the incoming list by the good one
Fixes #210
=> fix(issue#210): bad id for addReference id incoming list

.github/workflows/playwright.yml
This PR introduces a Github workflow for Playwright E2E testing.
Awaiting Review
=> Adding Playwright Github workflow

.golangci.yml
- Disable the "goconst" linter for the plugin.go file.
- The linter was giving some unnecessary lint errors.
Fixes: https://github.com/mattermost/mattermost-plugin-todo/pull/241#issuecomment-1904301497
=> [MM-161] Disable the "goconst" linter for plugin.go file

.github/workflows/playwright.yml, e2e/playwright/.eslintrc.json, e2e/playwright/package-lock.json, e2e/playwright/package.json
This pull request fix linting errors in the ```e2e/playwright``` directory.
Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/232
=> [GH-232]: Fix e2e playwright directory linting

webapp/src/components/user_selector/autocomplete_selector.tsx
Add a Max Length on user input.
Max length = 22
Fixe #150
=> fix(#150): add maxlength on input

webapp/src/components/assignee_modal/assignee_form.jsx, webapp/src/components/assignee_modal/assignee_modal.jsx, webapp/src/hooks/useEscapeKey.ts
- Fixed issue of todo getting assigned to last assigned user
- Can close unifinshed PR https://github.com/mattermost-community/mattermost-plugin-todo/pull/226
- Fixes #215 
- Assignee field is cleared and the old user is not assigned to the new todo after creating a todo
=> [MM-432] Fix issue of todo getting assigned to last assigned user
