mattermost-community/mattermost-plugin-todo

server/store.go

Delete items when removing them from the order
Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/28

[GH-28] Delete items when removing them from the order

---

README.md
plugin.json
server/bot.go
server/command.go
server/issue.go
server/list.go
server/manifest.go
server/plugin.go
server/store.go
webapp/src/actions.js
webapp/src/components/root/root.jsx
webapp/src/components/root/root.scss
webapp/src/components/sidebar_right/sidebar_right.jsx
webapp/src/components/sidebar_right/todo_issues.jsx
webapp/src/index.js
webapp/src/manifest.js

Now you can add a todo to a Thread. When you open the Add to do from the dot menu of a post, you will see now an option to add the todo to the thread.
When you create the todo, a message will be sent to the thread, and another message when the todo is deleted (by completing, cancelling, or "won't do"-ing it).
Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/25

Add todo to a thread

---

CODEOWNERS
README.md

Add CODEOWNERS file and maintainers to the README

Add CODEOWNERS and maintainers

---

server/command.go
server/list.go
server/plugin.go

Fix several messages that were not showing after some refactoring changes.
Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/48

[GH-48] Fix missing messages

---

server/command.go

Use bot account to post slash command responses
#4

Use bot account to post slash command responses

---

plugin.json
server/manifest.go
webapp/src/manifest.js

Tested locally and the link shows up in the Marketplace
https://community-release.mattermost.com/core/pl/mgrez65gjfngbbjqqho9ka1xte

Add Homepage and Support URL

---

webapp/src/action_types.js
webapp/src/actions.js
webapp/src/components/sidebar_buttons/index.js
webapp/src/components/sidebar_buttons/sidebar_buttons.jsx
webapp/src/components/sidebar_right/index.js
webapp/src/components/sidebar_right/sidebar_right.jsx
webapp/src/components/team_sidebar/index.js
webapp/src/components/team_sidebar/team_sidebar.jsx
webapp/src/constants.jsx
webapp/src/index.js
webapp/src/reducer.js

Resolves issue #24
Add 4 buttons on team sidebar as per issue
Buttons are - Your todos, requested todos, assigned todos, refresh
Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/24

Add todo button on team sidebar

---

webapp/src/components/post_type_todo/index.js
webapp/src/components/post_type_todo/post_type_todo.jsx

Render markdown on custom post types
#84

Render markdown on custom post types

---

build/sync/plan.yml
webapp/.gitignore

This file was not sync'd with the starter template in the previous PR

Sync webapp/.gitignore with starter template

---

webapp/src/components/root/root.jsx

This adds support markdown preview in the add todo modal.
Fixes https://github.com/mattermost/mattermost-plugin-todo/issues/21

[GH-21] Add support markdown preview in add todo modal

---

plugin.json
server/manifest.go
webapp/src/manifest.js

Fixes:
- https://github.com/mattermost/mattermost-plugin-todo/pull/156

Release bump 0.5.1

---

plugin.json
server/manifest.go
webapp/src/manifest.js

https://github.com/mattermost/mattermost-plugin-todo/issues/162

Bump release 0.6.0 for App Bar

---

webapp/src/components/assignee_modal/assignee_modal.jsx
webapp/src/components/todo_issues/todo_issues.jsx
webapp/src/components/user_selector/autocomplete_selector.tsx
webapp/src/widget/buttons/button.scss
webapp/src/widget/menu.scss
webapp/src/widget/menu.tsx
webapp/src/widget/menuItem.tsx

GH-173 - Assign modal fix
#173

GH-173 - Assign modal fix

---

webapp/src/components/add_issue/add_issue.jsx
webapp/src/components/add_issue/index.js
webapp/src/components/sidebar_right/sidebar_right.jsx
webapp/src/components/sidebar_right/sidebar_right.scss
webapp/src/components/todo_item/todo_item.jsx
webapp/src/widget/menu.scss

GH-177 - Minor UI tweaks and regression fix
- Adds permalink to the new line instead of the same line.
- Allowed shift + enter shortcut to add new line.
Fixes #177

GH-177 - Minor UI tweaks and regression fix

---

webapp/src/components/buttons/accept.jsx
webapp/src/components/sidebar_right/_todo-item.scss
webapp/src/components/sidebar_right/sidebar_right.jsx
webapp/src/components/sidebar_right/sidebar_right.scss
webapp/src/components/todo_item/todo_item.jsx
webapp/src/widget/todo_toast/todo_toast.scss

Minor UI Fixes for todo items

---

.golangci.yml
go.mod
go.sum

Fix linter errors caused by `golangci-lint` update
None

Fix linter errors

---

plugin.json
server/manifest.go
webapp/src/manifest.js

- #176
- #174
- #161
- #180
- #182
- #189
https://github.com/mattermost/mattermost-plugin-todo/issues/178

Bump to 0.7.0

---

plugin.json
server/manifest.go
webapp/src/manifest.js

- https://github.com/mattermost/mattermost-plugin-todo/pull/209
- https://github.com/mattermost/mattermost-plugin-todo/pull/205
- https://github.com/mattermost/mattermost-plugin-todo/pull/204
- https://github.com/mattermost/mattermost-plugin-todo/pull/197
- https://github.com/mattermost/mattermost-plugin-todo/pull/213

Release 0.7.1

---

webapp/src/actions.js

Restricting users to send TODO to only for the selected team members.

Restricted user acces to selected team members

---

.golangci.yml
server/plugin.go

https://github.com/mattermost/mattermost-plugin-todo/pull/242#issuecomment-1906501406

[MM-180] Fix lint errors in the repo

---

.github/workflows/playwright.yml

Disable playwright test cases for now since they are broken

Disable playwright test cases
